### ISSUE TITLE
不能用了吗

### ISSUE THREAD

**Issue by cos800** [ezshine/mstts-js#2]
```
获取Token...
创建webscoket连接...
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: Invalid handshake: invalid first line format
    at Connection.checkHandshake (/opt/homebrew/lib/node_modules/mstts-js/node_modules/nodejs-websocket/Connection.js:375:22)
    at Connection.readHandshake (/opt/homebrew/lib/node_modules/mstts-js/node_modules/nodejs-websocket/Connection.js:331:54)
    at Connection.doRead (/opt/homebrew/lib/node_modules/mstts-js/node_modules/nodejs-websocket/Connection.js:246:13)
    at TLSSocket.<anonymous> (/opt/homebrew/lib/node_modules/mstts-js/node_modules/nodejs-websocket/Connection.js:66:8)
    at TLSSocket.emit (node:events:513:28)
    at emitReadable_ (node:internal/streams/readable:590:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)
Emitted 'error' event on Connection instance at:
    at Connection.checkHandshake (/opt/homebrew/lib/node_modules/mstts-js/node_modules/nodejs-websocket/Connection.js:375:8)
    at Connection.readHandshake (/opt/homebrew/lib/node_modules/mstts-js/node_modules/nodejs-websocket/Connection.js:331:54)
    [... lines matching original stack trace ...]
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.9.0
```

**Comment by guoxiangke** [comment]
https://cndevapi.com/r/javascript/post-detail/15

https://github.com/dusionlike/mstts-js/commit/a418a3704f5d74585ae4f51d1d1f8516432a2bb2

Fixed

**Comment by ezshine** [comment]
fixed
